#porta de acesso: 8008
#usuario de acesso: Admin
#Senha de acesso: zabbix

---
version: "3.1"
networks:
  network-zabbix:
    driver: bridge
services:
  mysql_zabbix:
    container_name: mysql_zabbix
    image: mysql:5.7
    networks:
      - network-zabbix
    ports:
      - 3308:3306
    volumes:
      - ./zabbix/mysql:/var/lib/data
    environment:
      - MYSQL_ROOT_PASSWORD=roger
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Roger@9941
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    links:
      - mysql_zabbix
    restart: always
    ports:
      - 10051:10051
    volumes:
      - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    environment:
      - DB_SERVER_HOST=mysql_zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Roger@9941
    depends_on:
      - mysql_zabbix
  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    links:
      - mysql_zabbix
    restart: always
    ports:
      - 8008:8080
      - 443:8443
    environment:
      - DB_SERVER_HOST=mysql_zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Roger@9941
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mysql_zabbix
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    links:
      - mysql_zabbix
      - zabbix-server
    restart: always
    ports:
      - 3008:3000
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql_zabbix
      - zabbix-server
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.0.1
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - 10050:10050
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.18.0.1

